version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - .env # This will load both MongoDB Atlas and Upstash Valkey connection strings
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
